In [27]:
#Create model class
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self,n_features):
        super().__init__()
        self.linear1=nn.Linear(n_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out



In [28]:
# create dataset
x=torch.rand(10,5)

In [29]:
model=Model(x.shape[1])

# call forward pass
#model.forward(x)
model(x)

tensor([[0.4843],
        [0.4902],
        [0.4778],
        [0.4903],
        [0.4921],
        [0.4635],
        [0.4921],
        [0.4921],
        [0.4921],
        [0.4662]], grad_fn=<SigmoidBackward0>)

In [30]:
model.linear1.weight

Parameter containing:
tensor([[-0.4140, -0.2233, -0.3220,  0.0998, -0.0055],
        [ 0.1350, -0.2958, -0.1695,  0.3893, -0.0642],
        [ 0.0099, -0.3863,  0.0011,  0.4219,  0.3449]], requires_grad=True)

In [31]:
model.linear1.bias

Parameter containing:
tensor([-0.0766, -0.3376, -0.1872], requires_grad=True)

In [22]:
!pip install torchinfo

  Obtaining dependency information for torchinfo from https://files.pythonhosted.org/packages/72/25/973bd6128381951b23cdcd8a9870c6dcfc5606cb864df8eabd82e529f9c1/torchinfo-1.8.0-py3-none-any.whl.metadata


In [32]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [42]:
#using sequential container
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,n_features):
        super().__init__()
        self.network=nn.Sequential(nn.Linear(n_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid())

    def forward(self,features):
        out=self.network(features)  
        return out  
    

In [43]:
model=Model(x.shape[1])
model(x)

tensor([[0.4596],
        [0.4531],
        [0.4720],
        [0.4528],
        [0.4589],
        [0.4529],
        [0.4902],
        [0.4584],
        [0.4555],
        [0.4562]], grad_fn=<SigmoidBackward0>)